---
abstract: ~
author:
  - 'Sergey Zasenko'
build_requires:
  ExtUtils::MakeMaker: 6.62
  FindBin: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Test::More: 0.88
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Twiggy-Server-TLS
no_index:
  directory:
    - inc
    - t
requires:
  IO::Socket::SSL: 1.56
  Twiggy: 0.1010
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.0001_3
